### ISSUE TITLE
No (new) notification is shown if the max number of (old) events to show is reached

### ISSUE THREAD

**Issue by ghost** [q2apro/q2apro-on-site-notifications#14]
Here is the plugin bug description:
Suppose that the maximum number of events to show in notification box is set to 50. If a user has over 50 "new" notifications (say 60), then clicking on the notification link will not list any new notification at all.
Tested on Q2A 1.7 

Ref: http://www.question2answer.org/qa/46214/on-site-notifications-finally-know-how-to-reproduce-the-bug

**Comment by q2apro** [comment]
I tested that on my localhost, it works. 

- I limited the "Maximum number of events to show in notification box" to 1. 
- I got 3 new notifications.
- I clicked on the notify icon (it showed "3"). 
- The notify box poped out and showed the 1 event (since I limited it). 

Cannot reproduce. 

Are you really using the latest plugin version?
